DB_CONFIG = {
    "database": "tpch", #dsb
    "user": "",
    "password": "",
    "host": "localhost",
    "port": "", 
}

FLATTEN_RULES = [
    "FILTER_INTO_JOIN",
    "FILTER_CORRELATE",
]


PUSHDOWN_RULES = [
    "AGGREGATE_EXPAND_DISTINCT_AGGREGATES_TO_JOIN",
    "FILTER_PROJECT_TRANSPOSE",
    "FILTER_TABLE_FUNCTION_TRANSPOSE",
    "FILTER_AGGREGATE_TRANSPOSE",
    "FILTER_SCAN",
    "PROJECT_CORRELATE_TRANSPOSE",
    "SORT_JOIN_TRANSPOSE",
    "SORT_PROJECT_TRANSPOSE",
    "SORT_UNION_TRANSPOSE",
    "AGGREGATE_UNION_TRANSPOSE",
    "UNION_MERGE",
    "UNION_REMOVE",
    "UNION_TO_DISTINCT",
    "UNION_PULL_UP_CONSTANTS",
    "AGGREGATE_UNION_AGGREGATE",
    "AGGREGATE_UNION_TRANSPOSE",
    "JOIN_EXTRACT_FILTER",
    "JOIN_LEFT_UNION_TRANSPOSE",
    "JOIN_RIGHT_UNION_TRANSPOSE", 
    "JOIN_PROJECT_BOTH_TRANSPOSE",
    "JOIN_PROJECT_LEFT_TRANSPOSE",
    "JOIN_PROJECT_RIGHT_TRANSPOSE", 
    "SEMI_JOIN_REMOVE",
    "JOIN_REDUCE_EXPRESSIONS",
    "JOIN_CONDITION_PUSH"
] 


LOCAL_RULES = [
    "AGGREGATE_VALUES",
    "JOIN_REDUCE_EXPRESSIONS",

    'AGGREGATE_EXPAND_DISTINCT_AGGREGATES',
    'AGGREGATE_PROJECT_MERGE', 
    'AGGREGATE_ANY_PULL_UP_CONSTANTS',
    'AGGREGATE_UNION_AGGREGATE',
    'AGGREGATE_REMOVE',
    
    'FILTER_REDUCE_EXPRESSIONS',
    
    'PROJECT_REDUCE_EXPRESSIONS',
    'PROJECT_CALC_MERGE',
    'PROJECT_MERGE',
    'PROJECT_REMOVE',
    'PROJECT_TO_CALC',

    'SORT_PROJECT_TRANSPOSE',
    'SORT_UNION_TRANSPOSE',
    'SORT_REMOVE_CONSTANT_KEYS',
    'SORT_REMOVE',
    'SORT_FETCH_ZERO_INSTANCE',

    'CALC_MERGE',
    'CALC_REMOVE',
    
    'AGGREGATE_INSTANCE',
    'FILTER_INSTANCE', 
    'JOIN_LEFT_INSTANCE',
    'JOIN_RIGHT_INSTANCE',
    'PROJECT_INSTANCE',
    'SORT_INSTANCE',
    'UNION_INSTANCE',
    'INTERSECT_INSTANCE',
    'MINUS_INSTANCE'
]
